### ISSUE TITLE
Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by duataud** [ghondar/PelisTime-Mobile#1]
Hi! I'm trying to run it and see how to use "react-native-torrent-streamer" but unfortunately I get  the red screen with that message . Thanks 

Android 4.3

![screenshot_2016-04-04-12-27-41](https://cloud.githubusercontent.com/assets/9934327/14257012/291e6cf4-fa61-11e5-94e9-f05030f57bcb.png)

**Comment by ghondar** [comment]
Solved 9ed4970a7819caabb257cab73111ea3419ae155b, thanks for report
